//update


import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.SourceDataLine;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Al-amin
 */


public class NewJFrame extends javax.swing.JFrame{

    /**
     * Creates new form NewJFrame
     */
    
    ArrayList<Thread> keyThread;
    
    public NewJFrame() {
        keyThread = new ArrayList<>();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String DetectKey(java.awt.event.KeyEvent evt){
        String filename = null;
        try{
            //System.out.println(evt.getKeyChar());
            //filename = "\\wav\\"+evt.getKeyChar()+".wav";
            filename = evt.getKeyChar()+".wav";
        }catch(Exception e){
            System.out.println("Event could not be detected");
        }
        return(filename);
    }
    public void Play(String filename)
	{
            try{
                //SoundClipTest sound = new SoundClipTest();
                playSound("src\\wav\\"+filename);
            } catch(Exception e){
                System.out.println("exception in play()");
            }            
	}
    
    private final int BUFFER_SIZE = 128000;
    private File soundFile;
    private AudioInputStream audioStream;
    private AudioFormat audioFormat;
    private SourceDataLine sourceLine;
    
    public void playSound(String filename){

        String strFilename = filename;

        try {
            soundFile = new File(strFilename);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }

        try {
            audioStream = AudioSystem.getAudioInputStream(soundFile);
        } catch (Exception e){
            e.printStackTrace();
            System.exit(1);
        }

        audioFormat = audioStream.getFormat();

        DataLine.Info info = new DataLine.Info(SourceDataLine.class, audioFormat);
        try {
            sourceLine = (SourceDataLine) AudioSystem.getLine(info);
            sourceLine.open(audioFormat);
        } catch (LineUnavailableException e) {
            e.printStackTrace();
            System.exit(1);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }

        sourceLine.start();

        int nBytesRead = 0;
        byte[] abData = new byte[BUFFER_SIZE];
        while (nBytesRead != -1) {
            try {
                nBytesRead = audioStream.read(abData, 0, abData.length);
            } catch (IOException e) {
                e.printStackTrace();
            }
            if (nBytesRead >= 0) {
                @SuppressWarnings("unused")
                int nBytesWritten = sourceLine.write(abData, 0, nBytesRead);
            }
        }

        sourceLine.drain();
        sourceLine.close();
    }
        /*AudioInputStream audioIn = null;
        URL url;
        Clip clip = null;
    public void PlaySound(String filename) {
      /*this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.setTitle("Test Sound Clip");
      this.setSize(300, 200);
      this.setVisible(true);
   
      
      try {
         // Open an audio input stream.
         url = this.getClass().getClassLoader().getResource(filename);
         audioIn = AudioSystem.getAudioInputStream(url);
         // Get a sound clip resource.
         clip = AudioSystem.getClip();
         // Open audio clip and load samples from the audio input stream.
         clip.open(audioIn);
         clip. start();
         //audioIn.close();
      } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
      }finally{
        try{
            audioIn.close();
            //clip.close();
        }catch(Exception ex){
        System.out.println("not closed");
            }
        }
   }*/
    /*
        //make a new thread for each new keyPressed event
        //& play the corresponding sounds symultaniously
        //destroy every thread for the keyReleased event
    */
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println("key pressed "+evt.getKeyChar());
        try{
            
            String keyFileName = DetectKey(evt);

            Thread thread = new Thread(){
            public void run(){
                System.out.println("Thread: " + getName() + " running");
              //Play("\\wav\\"+DetectKey(evt));
                Play(keyFileName);
            }
          };

            thread.setName(keyFileName);
            keyThread.add(thread);
            thread.start();

       }catch(Exception e){
           System.out.println("Exception in creating Thread");
       
    }//GEN-LAST:event_formKeyPressed
}
    public Thread getThreadByName(String threadName) {

        /***
            Searching the thread from save list;
        */
    for(int index=0;index < keyThread.size();index++){
        Thread thread  = keyThread.get(index);
        if(thread.getName().equals(threadName)){
            System.out.println(threadName + " Thread Found!");
            return thread;
        }
    }


    /*for (Thread t : Thread.getAllStackTraces().keySet()) {
        if (t.getName().equals(threadName))
            return t;
    }*/

    return null;
}
     public void deleteKeyThreadItem(String threadName){

   	for(int index=0;index<keyThread.size();index++){

       Thread thread  = keyThread.get(index);

       if(thread.getName().equals(threadName)){

           keyThread.remove(index);
       }
   }
}

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        System.out.println("key releassed "+evt.getKeyChar());
        //System.out.println("closing Thread "+getThreadByName(evt.getKeyChar()+".wav"));

        String keyFileName = evt.getKeyChar()+".wav";
        Thread thread = getThreadByName(keyFileName);
        //thread = null;
        deleteKeyThreadItem(keyFileName);
        System.out.println(thread+" deleted");

    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
